<?php

namespace ContainerJEw0XAQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFicheDePosteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.X_C37gB.App\Entity\FicheDePoste' shared service.
     *
     * @return \App\Entity\FicheDePoste
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.X_C37gB": it needs an instance of "App\\Entity\\FicheDePoste" but this type has been excluded in "config/services.yaml".');
    }
}
