<?php

namespace ContainerJEw0XAQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationControllerregisterDevService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KAWHxDW.App\Controller\RegistrationController::registerDev()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KAWHxDW.App\\Controller\\RegistrationController::registerDev()'] = ($container->privates['.service_locator.KAWHxDW'] ?? $container->load('get_ServiceLocator_KAWHxDWService'))->withContext('App\\Controller\\RegistrationController::registerDev()', $container);
    }
}
