<?php

namespace ContainerIhMJQtS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UOf025LService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uOf025L' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uOf025L'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\DevDashboardController::index' => ['privates', '.service_locator.GmDnOX4.App\\Controller\\DevDashboardController::index()', 'getDevDashboardControllerindexService', true],
            'App\\Controller\\DevDashboardController::profile' => ['privates', '.service_locator.egipcEH.App\\Controller\\DevDashboardController::profile()', 'getDevDashboardControllerprofileService', true],
            'App\\Controller\\EntrepriseDashboardController::index' => ['privates', '.service_locator.Hqg49at.App\\Controller\\EntrepriseDashboardController::index()', 'getEntrepriseDashboardControllerindexService', true],
            'App\\Controller\\EntrepriseDashboardController::editProfile' => ['privates', '.service_locator.egipcEH.App\\Controller\\EntrepriseDashboardController::editProfile()', 'getEntrepriseDashboardControllereditProfileService', true],
            'App\\Controller\\EntrepriseDashboardController::newFichePoste' => ['privates', '.service_locator.egipcEH.App\\Controller\\EntrepriseDashboardController::newFichePoste()', 'getEntrepriseDashboardControllernewFichePosteService', true],
            'App\\Controller\\EntrepriseDashboardController::showFichePoste' => ['privates', '.service_locator.X_C37gB.App\\Controller\\EntrepriseDashboardController::showFichePoste()', 'getEntrepriseDashboardControllershowFichePosteService', true],
            'App\\Controller\\EntrepriseDashboardController::editFichePoste' => ['privates', '.service_locator.g_caA00.App\\Controller\\EntrepriseDashboardController::editFichePoste()', 'getEntrepriseDashboardControllereditFichePosteService', true],
            'App\\Controller\\EntrepriseDashboardController::deleteFichePoste' => ['privates', '.service_locator.g_caA00.App\\Controller\\EntrepriseDashboardController::deleteFichePoste()', 'getEntrepriseDashboardControllerdeleteFichePosteService', true],
            'App\\Controller\\HomeController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\HomeController::login()', 'getHomeControllerloginService', true],
            'App\\Controller\\RegistrationController::registerDev' => ['privates', '.service_locator.KAWHxDW.App\\Controller\\RegistrationController::registerDev()', 'getRegistrationControllerregisterDevService', true],
            'App\\Controller\\RegistrationController::registerCompany' => ['privates', '.service_locator.KAWHxDW.App\\Controller\\RegistrationController::registerCompany()', 'getRegistrationControllerregisterCompanyService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\DevDashboardController:index' => ['privates', '.service_locator.GmDnOX4.App\\Controller\\DevDashboardController::index()', 'getDevDashboardControllerindexService', true],
            'App\\Controller\\DevDashboardController:profile' => ['privates', '.service_locator.egipcEH.App\\Controller\\DevDashboardController::profile()', 'getDevDashboardControllerprofileService', true],
            'App\\Controller\\EntrepriseDashboardController:index' => ['privates', '.service_locator.Hqg49at.App\\Controller\\EntrepriseDashboardController::index()', 'getEntrepriseDashboardControllerindexService', true],
            'App\\Controller\\EntrepriseDashboardController:editProfile' => ['privates', '.service_locator.egipcEH.App\\Controller\\EntrepriseDashboardController::editProfile()', 'getEntrepriseDashboardControllereditProfileService', true],
            'App\\Controller\\EntrepriseDashboardController:newFichePoste' => ['privates', '.service_locator.egipcEH.App\\Controller\\EntrepriseDashboardController::newFichePoste()', 'getEntrepriseDashboardControllernewFichePosteService', true],
            'App\\Controller\\EntrepriseDashboardController:showFichePoste' => ['privates', '.service_locator.X_C37gB.App\\Controller\\EntrepriseDashboardController::showFichePoste()', 'getEntrepriseDashboardControllershowFichePosteService', true],
            'App\\Controller\\EntrepriseDashboardController:editFichePoste' => ['privates', '.service_locator.g_caA00.App\\Controller\\EntrepriseDashboardController::editFichePoste()', 'getEntrepriseDashboardControllereditFichePosteService', true],
            'App\\Controller\\EntrepriseDashboardController:deleteFichePoste' => ['privates', '.service_locator.g_caA00.App\\Controller\\EntrepriseDashboardController::deleteFichePoste()', 'getEntrepriseDashboardControllerdeleteFichePosteService', true],
            'App\\Controller\\HomeController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\HomeController::login()', 'getHomeControllerloginService', true],
            'App\\Controller\\RegistrationController:registerDev' => ['privates', '.service_locator.KAWHxDW.App\\Controller\\RegistrationController::registerDev()', 'getRegistrationControllerregisterDevService', true],
            'App\\Controller\\RegistrationController:registerCompany' => ['privates', '.service_locator.KAWHxDW.App\\Controller\\RegistrationController::registerCompany()', 'getRegistrationControllerregisterCompanyService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\DevDashboardController::index' => '?',
            'App\\Controller\\DevDashboardController::profile' => '?',
            'App\\Controller\\EntrepriseDashboardController::index' => '?',
            'App\\Controller\\EntrepriseDashboardController::editProfile' => '?',
            'App\\Controller\\EntrepriseDashboardController::newFichePoste' => '?',
            'App\\Controller\\EntrepriseDashboardController::showFichePoste' => '?',
            'App\\Controller\\EntrepriseDashboardController::editFichePoste' => '?',
            'App\\Controller\\EntrepriseDashboardController::deleteFichePoste' => '?',
            'App\\Controller\\HomeController::login' => '?',
            'App\\Controller\\RegistrationController::registerDev' => '?',
            'App\\Controller\\RegistrationController::registerCompany' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\DevDashboardController:index' => '?',
            'App\\Controller\\DevDashboardController:profile' => '?',
            'App\\Controller\\EntrepriseDashboardController:index' => '?',
            'App\\Controller\\EntrepriseDashboardController:editProfile' => '?',
            'App\\Controller\\EntrepriseDashboardController:newFichePoste' => '?',
            'App\\Controller\\EntrepriseDashboardController:showFichePoste' => '?',
            'App\\Controller\\EntrepriseDashboardController:editFichePoste' => '?',
            'App\\Controller\\EntrepriseDashboardController:deleteFichePoste' => '?',
            'App\\Controller\\HomeController:login' => '?',
            'App\\Controller\\RegistrationController:registerDev' => '?',
            'App\\Controller\\RegistrationController:registerCompany' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);
    }
}
