<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Entreprise extends \App\Entity\Entreprise implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'fichesDePoste' => [parent::class, 'fichesDePoste', null],
        "\0".parent::class."\0".'logo' => [parent::class, 'logo', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'siteWeb' => [parent::class, 'siteWeb', null],
        "\0".'App\\Entity\\User'."\0".'email' => ['App\\Entity\\User', 'email', null],
        "\0".'App\\Entity\\User'."\0".'id' => ['App\\Entity\\User', 'id', null],
        "\0".'App\\Entity\\User'."\0".'password' => ['App\\Entity\\User', 'password', null],
        "\0".'App\\Entity\\User'."\0".'role' => ['App\\Entity\\User', 'role', null],
        'adresse' => [parent::class, 'adresse', null],
        'description' => [parent::class, 'description', null],
        'email' => ['App\\Entity\\User', 'email', null],
        'fichesDePoste' => [parent::class, 'fichesDePoste', null],
        'id' => ['App\\Entity\\User', 'id', null],
        'logo' => [parent::class, 'logo', null],
        'nom' => [parent::class, 'nom', null],
        'password' => ['App\\Entity\\User', 'password', null],
        'role' => ['App\\Entity\\User', 'role', null],
        'siteWeb' => [parent::class, 'siteWeb', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
