<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerODfMxmk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerODfMxmk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerODfMxmk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerODfMxmk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerODfMxmk\App_KernelDevDebugContainer([
    'container.build_hash' => 'ODfMxmk',
    'container.build_id' => '72684d23',
    'container.build_time' => 1736555994,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerODfMxmk');
